format = """$directory$git_branch$git_status$cmd_duration$status
$character"""

command_timeout = 100

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[git_status]
format = '[$conflicted$stashed$staged$modified$untracked$ahead_behind]($style) '
style = "red"
modified = " "
staged = " "
stashed = " "
conflicted = " "
untracked = "? "
ahead = " "
behind = " "
diverged = " "
ignore_submodules = true

[git_branch]
format = "[ $branch]($style) "
style = "blue"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[directory]
format = "[ $path]($style) "
truncation_length = 3
style = "magenta"
truncate_to_repo = true

[cmd_duration]
format = "[took $duration]($style) "
style = "bright-black"

[status]
disabled = false
format = "[exit $status]($style) "
style = "red"

[character]
success_symbol = "[❯](magenta)"
error_symbol = "[❯](red)"
