local bg = { bg = "NONE" }

return {
  "akinsho/bufferline.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  version = "*",
  event = "VeryLazy",
  opts = {
    highlights = {
      fill = bg,
      background = bg,
      tab = bg,
      tab_selected = bg,
      tab_close = bg,
      tab_separator = bg,
      tab_separator_selected = bg,
      buffer_visible = bg,
      buffer_selected = { bg = "NONE", bold = true, italic = false },
      separator = bg,
      separator_visible = bg,
      separator_selected = bg,
      close_button = bg,
      close_button_visible = bg,
      close_button_selected = bg,
      modified = bg,
      modified_visible = bg,
      modified_selected = bg,
      duplicate = bg,
      duplicate_visible = bg,
      duplicate_selected = bg,
      indicator_visible = bg,
      indicator_selected = bg,
      numbers = bg,
      numbers_visible = bg,
      numbers_selected = bg,
      diagnostic = bg,
      diagnostic_visible = bg,
      diagnostic_selected = bg,
      hint = bg,
      hint_visible = bg,
      hint_selected = bg,
      hint_diagnostic = bg,
      hint_diagnostic_visible = bg,
      hint_diagnostic_selected = bg,
      info = bg,
      info_visible = bg,
      info_selected = bg,
      info_diagnostic = bg,
      info_diagnostic_visible = bg,
      info_diagnostic_selected = bg,
      warning = bg,
      warning_visible = bg,
      warning_selected = bg,
      warning_diagnostic = bg,
      warning_diagnostic_visible = bg,
      warning_diagnostic_selected = bg,
      error = bg,
      error_visible = bg,
      error_selected = bg,
      error_diagnostic = bg,
      error_diagnostic_visible = bg,
      error_diagnostic_selected = bg,
      offset_separator = bg,
      trunc_marker = bg,
      pick = bg,
      pick_visible = bg,
      pick_selected = bg,
    },
  },
}
