# STATUS BAR STYLE - COOLNIGHT
# palette: bg=#011423 surface=#214969 gray=#547998 fg=#CBE0F0 cyan=#24EAF7 magenta=#a277ff prefix=#a277ff
set -g status-left '#{?client_prefix,#[fg=#a277ff#,bg=default]#[fg=#011423#,bg=#a277ff]  #S #[fg=#a277ff#,bg=default],#[fg=#24EAF7#,bg=default]#[fg=#011423#,bg=#24EAF7]  #S #[fg=#24EAF7#,bg=default]}#[fg=#24EAF7,bg=default] |'
set -g status-right '#[fg=#24EAF7,bg=default]#[fg=#24EAF7,bg=default]| #[fg=#24EAF7,bg=default]#[fg=#011423,bg=#24EAF7]%m/%d/%y#[fg=#24EAF7,bg=default]'
set -g window-status-current-format '#[fg=#24EAF7,bg=default] #[fg=#011423,bg=#24EAF7]#I#W#[fg=#24EAF7,bg=default]'
set -g window-status-format '#[fg=#547998,bg=default]  #I #W '

set -g window-status-last-style 'fg=#CBE0F0,bg=default'
set -g pane-border-style 'fg=#547998'
set -g pane-active-border-style 'fg=#24EAF7'
set -g message-command-style bg=default,fg=#CBE0F0
set -g message-style bg=default,fg=#CBE0F0
set -g mode-style bg=#547998,fg=#CBE0F0
