[mgr]
border_style = { fg = "darkgray" }
cwd = { fg = "lightblue" }
hovered = { bg = "black", fg = "reset", bold = true }
preview_hovered = { bg = "black", fg = "reset", bold = true }
find_keyword = { fg = "lightgreen", bold = true }
find_position = { fg = "darkgray" }
marker_selected = { bg = "black", fg = "lightmagenta" }
marker_copied = { bg = "green", fg = "green" }
marker_cut = { bg = "red", fg = "red" }
tab_active = { bg = "blue", fg = "black" }
tab_inactive = { bg = "black", fg = "darkgray" }

count_selected = { bg = "magenta", fg = "black" }
count_copied = { bg = "green", fg = "black" }
count_cut = { bg = "red", fg = "black" }

[status]
separator_open = ""
separator_close = ""
mode_normal = { bg = "blue", fg = "black", bold = true }
mode_select = { bg = "green", fg = "black", bold = true }
mode_unset = { bg = "red", fg = "black", bold = true }
permissions_r = { fg = "cyan" }
permissions_w = { fg = "red" }
permissions_x = { fg = "green" }
permissions_s = { fg = "darkgray" }
permissions_t = { fg = "blue" }
progress_label = { fg = "reset" }
progress_normal = { fg = "blue" }
progress_error = { fg = "red" }

[completion]
active = { bg = "black", fg = "magenta" }
inactive = { fg = "darkgray" }
border = { fg = "darkgray" }

[input]
border = { fg = "darkgray" }
title = { fg = "reset" }
value = { fg = "reset" }
selected = { bg = "black" }

[select]
active = { fg = "magenta" }
inactive = { fg = "darkgray" }
border = { fg = "darkgray" }

[help]
on = { fg = "magenta" }
run = { fg = "cyan" }
desc = { fg = "darkgray" }
hovered = { bg = "black", fg = "reset" }
footer = { fg = "darkgray" }

[filetype]
rules = [
  { mime = "image/*", fg = "cyan" },
  { mime = "video/*", fg = "cyan" },
  { mime = "audio/*", fg = "cyan" },
  { mime = "application/zip", fg = "magenta" },
  { mime = "application/gzip", fg = "magenta" },
  { mime = "application/x-tar", fg = "magenta" },
  { mime = "application/x-bzip", fg = "magenta" },
  { mime = "application/x-bzip2", fg = "magenta" },
  { mime = "application/x-7z-compressed", fg = "magenta" },
  { mime = "application/x-rar", fg = "magenta" },
  { mime = "application/pdf", fg = "red" },
  { mime = "inode/directory", fg = "blue", bold = true },
  { mime = "*", fg = "reset" },
]

[tasks]
border = { fg = "darkgray" }
title = { fg = "reset" }
hovered = { bg = "black", fg = "reset" }

[which]
mask = { bg = "black" }
cand = { fg = "cyan" }
rest = { fg = "darkgray" }
desc = { fg = "darkgray" }
separator_style = { fg = "darkgray" }
